import Link from "next/link";

export const metadata = { title: "Terms of Use — Backpackervun Travel Planner" };

export default function TermsPage() {
  return (
    <div className="min-h-screen paper-bg">
      <div className="mx-auto max-w-2xl px-4 py-14 sm:px-6">
        <BackLink />
        <h1 className="mt-6 text-3xl font-semibold tracking-tight text-ink">Terms of Use</h1>
        <p className="mt-2 text-sm text-ink-muted">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>

        <div className="mt-8 space-y-8 text-sm text-ink-soft leading-relaxed">
          <Section title="1. Informational use only">
            <p>Backpackervun Travel Planner is provided as a planning and organisational tool to help you draft travel itineraries. All content, estimates, route suggestions, and budgets displayed are for informational purposes only and do not constitute professional travel advice.</p>
          </Section>

          <Section title="2. Pricing and availability">
            <p>Transport fares, hotel rates, attraction admission fees, and any other prices you see or enter into this app may change without notice. Backpackervun does not guarantee the accuracy of any rates or pricing information. You are responsible for verifying current prices with the relevant service providers before making any bookings.</p>
          </Section>

          <Section title="3. User responsibility">
            <p>You are solely responsible for:</p>
            <ul className="mt-2 list-disc pl-5 space-y-1">
              <li>Verifying all itinerary details before travel</li>
              <li>Making your own bookings through third-party providers</li>
              <li>Ensuring visa, entry, and health requirements are met</li>
              <li>The accuracy of any data you enter into this app</li>
            </ul>
          </Section>

          <Section title="4. Third-party services">
            <p>This app provides links to third-party booking platforms (e.g. Google Flights, Klook, FlixBus). Backpackervun is not responsible for changes, cancellations, errors, or losses arising from your use of those platforms. Your relationship is directly with those third-party providers.</p>
          </Section>

          <Section title="5. No liability">
            <p>To the fullest extent permitted by applicable law, Backpackervun shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of this travel planner or any bookings made based on information generated by it.</p>
          </Section>

          <Section title="6. Changes to these terms">
            <p>We may update these Terms of Use at any time. Continued use of the app constitutes acceptance of the updated terms.</p>
          </Section>
        </div>

        <div className="mt-12 border-t border-paper-line pt-6 text-center">
          <p className="text-xs text-ink-muted">Questions? <a href="mailto:info@backpackervun.com" className="text-navy-500 hover:underline">info@backpackervun.com</a></p>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <h2 className="text-base font-semibold text-ink mb-3">{title}</h2>
      {children}
    </div>
  );
}

function BackLink() {
  return (
    <Link href="/dashboard" className="inline-flex items-center gap-1.5 text-sm text-navy-500 hover:underline underline-offset-2">
      <svg viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5"/><path d="M12 5l-7 7 7 7"/></svg>
      Back to planner
    </Link>
  );
}
